/* 1. Afishoni te dhenat per punonjesit qe filluan punen ne vitin 2012. */

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE >= TO_DATE('2012-01-01', 'YYYY-MM-DD');


/* 2. Afishoni emrin,mbiemrin,numrin dhe emrin e deparamentit per secilin punonjes. */

SELECT FIRST_NAME, LAST_NAME, PHONE_NUMBER, DEPARTMENT_NAME
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

/* 3. Afishoni emrin,mbiemrin, deparamentin,qytetin dhe shetin per secilin punonjes. */

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
LEFT JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
LEFT JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;

/* 4. Afishoni emrin,mbiemrin,emrin dhe id e departementit per te gjithe departamentet edhe per ato qe nuk kane punonjes. */

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, DEPARTMENTS.DEPARTMENT_ID
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

/* 5. Afishoni emrin e punonjesit dhe menaxherit edhe per punonjesit qe nuk kane menaxher. */

SELECT E.FIRST_NAME AS EMPLOYEE, M.FIRST_NAME AS MANAGER
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID;

/*6. Afishoni emrin e departamentit,rrogen mesatare dhe numrin e punonjesve per ata punonjes qe marrin komision ne ate department */

SELECT DEPARTMENT_NAME, ROUND(AVG(SALARY), 2) AS "PAGA MESATARE", COUNT(*) AS "NUMRI PUNONJESVE"
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY (DEPARTMENT_NAME);

/*7. Afishoni departamntin,emrin e menaxherit dhe rrogen e menaxherve qe kane experience me shume se 5 vjet. */

SELECT DISTINCT M.EMPLOYEE_ID AS MANAGER_ID,CONCAT(M.FIRST_NAME, M.LAST_NAME) AS "EMRI MENAXHERIT", DEPARTMENT_NAME, M.SALARY AS PAGA
FROM EMPLOYEES M
JOIN EMPLOYEES E ON M.EMPLOYEE_ID = E.MANAGER_ID
LEFT JOIN DEPARTMENTS D ON M.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE MONTHS_BETWEEN(SYSDATE, M.HIRE_DATE) > 60;

/*8. Afishoni shtetin ,qytetin dhe numrin e departamenteve qe kane te pakten 2 punonjes. */

SELECT C.COUNTRY_NAME, L.CITY, COUNT(DISTINCT D.DEPARTMENT_ID) AS "NUMRI DEPARTAMENTEVE"
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY C.COUNTRY_NAME, L.CITY
HAVING COUNT(EMPLOYEE_ID) >= 2;

/*9. Afishoni emrin e plote,punen,daten e fillimit dhe te mbarimit te punes se fundit per punonjesit qe kane punuar pa perqindje komisioni. */

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMRI, J.JOB_TITLE, H.START_DATE, H.END_DATE
FROM EMPLOYEES E
LEFT JOIN JOB_HISTORY H ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
JOIN JOBS J ON H.JOB_ID = J.JOB_ID
WHERE E.COMMISSION_PCT IS NULL
AND H.END_DATE = (

    SELECT MAX(H2.END_DATE)
    FROM JOB_HISTORY H2
    WHERE H2.EMPLOYEE_ID = E.EMPLOYEE_ID

    );

/*10. Afishoni emrin e punonjesve per ate punonjes qe ka me shume vite se menaxheri I tij. */
--Nese kerkohet menaxheri i punonjesit
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMRI
FROM EMPLOYEES E
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.HIRE_DATE < M.HIRE_DATE;

--Nese kerkohet menaxheri i departamentit ku ben pjese punonjesi

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMRI
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN EMPLOYEES DM ON D.MANAGER_ID = DM.EMPLOYEE_ID
WHERE E.HIRE_DATE < DM.HIRE_DATE;
